---
- name: Install node-exporter
  become: true
  apt:
    update_cache: true
    state: present
    install_recommends: false
    name:
      - prometheus-node-exporter
  register: task_result
  until: task_result is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"

- name: Configure node-exporter
  become: true
  template:
    src: prometheus-node-exporter.j2
    dest: /etc/default/prometheus-node-exporter
    owner: root
    group: root
    mode: 0640

- name: Restart node-exporter
  become: true
  systemd:
    name: prometheus-node-exporter
    state: restarted
    enabled: true
    daemon-reload: true
...
