---
- name: Initialize node connection
  import_playbook: "connect-to-nodes.yaml"

- name: Fail if node got not bootstrapped once, yet
  any_errors_fatal: true
  hosts: all:!orchestrator
  tasks:
  - name: Fail if node got not bootstrapped once, yet
    when: not ansible_local['bootstrap']['bootstrapped'] | default(False) | bool
    fail:
      msg: |
        ERROR

        We're at an advanced stage of the rollout,
        but the node did not get bootstrapped yet!
        Please ensure the k8s-core/bootstrap playbook
        is executed at least once against every node
        before proceeding.
        This is automatically done if the install-all
        playbook of either k8s-core or k8s-supplements is executed.

- name: Clean up control plane
  hosts: masters
  gather_facts: true
  serial: 1
  roles:
  - role: etcd-clean-stale-members
    when: ansible_local['kubernetes-initialized']['k8s_install_status'] | default('not_initialized') == 'initialized'
    tags: etcd-clean-stale-members

- name: Spawn the K8s control plane
  hosts: masters
  gather_facts: true
  vars_files:
  - vars/disruption.yaml
  - vars/auto_generated_preamble.yaml
  - vars/etc.yaml
  - vars/retries.yaml
  - vars/vault-config.yaml
  - vars/node-labels.yaml
  serial:
  - 1
  - "100%"
  roles:
  - role: audit-logs
  - role: k8s-master
    tags: k8s-master
  - role: cluster-health-verification
    delegate_to: "{{ groups['orchestrator'] | first }}"

- name: Spawn and configure the K8s worker nodes
  hosts: workers
  gather_facts: true
  vars_files:
  - vars/disruption.yaml
  - vars/auto_generated_preamble.yaml
  - vars/etc.yaml
  - vars/retries.yaml
  - vars/vault-config.yaml
  - vars/node-labels.yaml
  roles:
  - role: k8s-worker
    tags: k8s-worker

- name: Configure Kubelet of K8s nodes
  hosts: k8s_nodes
  gather_facts: true
  vars_files:
  - vars/disruption.yaml
  roles:
  - role: kubelet-configuration
    tags: kubelet-configuration

- name: Configure Nvidia Device Plugin
  hosts: workers
  vars_files:
  - vars/retries.yaml
  roles:
  - role: nvidia-device-plugin
    when: k8s_is_gpu_cluster and not k8s_virtualize_gpu
    tags:
    - gpu-support
    - nvidia-device-plugin
...
