---
# TODO: @deprecated::debian12 @deprecated::ubuntu2404
# Drop the conditionals and stick to bird3 once Debian 12 and Ubuntu 24.04 reached EOL
bird_package: >-
  {{ 'bird'
      if ((ansible_distribution == 'Debian' and ansible_distribution_major_version < '13')
          or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version < '26'))
      else 'bird3' }}
...
