---
- name: Ensure /etc/containerd directory is present
  become: true
  file:
    path: /etc/containerd
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Install containerd
  become: true
  # Only do changes to the package if disruption is explicitly allowed
  # or if Kubernetes is not initialized on the node, yet
  when:
  - |
    _allow_disruption
    or ansible_local['kubernetes-initialized']['k8s_install_status'] | default('not_initialized') != 'initialized'
  block:
  - name: Add docker repository
    block:
    - name: Ensure keyrings directory exists
      # ftr: this is present by default on Debian...
      file:
        state: directory
        path: /etc/apt/keyrings
        owner: root
        group: root
        mode: u=rwx,go=rx

    - name: Add GPG apt key
      copy:
        src: apt-key-{{ ansible_distribution | lower }}.gpg
        dest: /etc/apt/keyrings/docker.gpg
        owner: root
        group: root
        mode: u=rw,go=r

    - name: Add docker repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/docker.gpg] {% if apt_proxy_url is not none %}http{% else %}https{% endif %}://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
      register: apt_action
      until: apt_action is not failed
      retries: "{{ error_retries }}"
      delay: "{{ error_delay }}"

    - name: Update apt package cache
      apt:
        update_cache: true
      register: apt_action
      until: apt_action is not failed
      retries: "{{ error_retries }}"
      delay: "{{ error_delay }}"

  - name: Install 'containerd.io' package from docker repository
    block:
    - name: Install 'containerd.io' package from docker repository
      apt:
        name:
        - "containerd.io={{ containerd_version }}-*"
        allow_downgrade: true
        allow_change_held_packages: true
      register: package_install
      until: package_install is not failed
      retries: "{{ error_retries }}"
      delay: "{{ error_delay }}"

    - name: Prevent the 'containerd.io' package from being updated automatically  # noqa no-changed-when
      command: apt-mark hold containerd.io

- name: Create containerd daemon configuration
  become: true
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: 0640
  register: configuration_update

- name: Ensure /etc/systemd/system/containerd.service.d/ is present
  become: true
  file:
    path: /etc/systemd/system/containerd.service.d
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Require containerd to be started before kubelet
  become: true
  copy:
    src: before-kubelet.conf
    dest: /etc/systemd/system/containerd.service.d/before-kubelet.conf
    owner: root
    group: root
    mode: 0640
  register: configuration_update

# Starting with containerd 2.0 this option has been removed and the default is used:
# https://github.com/containerd/containerd/blob/main/docs/containerd-2.0.md#limitnofile-configuration-has-been-removed
- name: Ensure limit-nofile drop-in
  become: true
  copy:
    src: limit-nofile.conf
    dest: /etc/systemd/system/containerd.service.d/limit-nofile.conf
    owner: root
    group: root
    mode: 0640
  register: configuration_update_limit_nofile

- name: Configure crictl
  become: true
  template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
    owner: root
    group: root
    mode: 0400

- name: Mirror management
  become: true
  block:
  - name: Create the containerd mirror directory
    file:
      path: /etc/containerd/certs.d
      state: directory
      # WARNING: The certs.d directory is world readable.  It may
      # contain private keys for client key authentication in the
      # future. Make sure to set restrictive file permissions on those.
      mode: 0755
      owner: root
      group: root

  - name: Configure containerd mirrors
    # NOTE: containerd need not be reloaded for changes to the mirrors
    # to take effect.
    include_tasks:
      file: configure-mirror.yaml
    loop: "{{ containerd_mirrors }}"

  - name: Remove containerd mirrors not configured
    block:
    - name: Get a list of configured registry mirrors
      find:
        paths: /etc/containerd/certs.d/
        recurse: false
        file_type: directory
      register: configured_registry_mirrors

    - name: "Deconfigure legacy registry mirrors"
      when: (item | basename) not in (containerd_mirrors | map(attribute='registry'))
      file:
        state: absent
        path: "{{ item }}"
      loop: "{{ configured_registry_mirrors.files | selectattr('path', 'defined') | map(attribute='path') }}"

- name: Restart containerd  # noqa no-handler
  become: true
  # Only restart if something changed AND we're allowed to do the restart
  when:
  - package_install.changed or configuration_update.changed or configuration_update_limit_nofile.changed
  - |
    _allow_disruption
    or ansible_local['kubernetes-initialized']['k8s_install_status'] | default('not_initialized') != 'initialized'
  systemd:
    enabled: true
    state: restarted
    daemon_reload: true
    name: containerd
...
