---
# LCM managed Kubernetes node labels for each Ansible host group
# see docs ref:cluster.node-labeling
# NOTE: Labels set to `null` will be removed if they exist
_managed_node_labels:
  masters:
    node-role.kubernetes.io/control-plane: ""
    node-role.kubernetes.io/worker: null
  workers:
    node-role.kubernetes.io/worker: ""
    node-role.kubernetes.io/control-plane: null
    # k8s.yaook.cloud/gpu-node: true  # is set conditionally
    # TODO: support conditional managed node labels
...
