variables:
  YAOOK_K8S_RELEASE_BRANCH_PREFIX: release/v
  YAOOK_K8S_RELEASE_PREPARE_BRANCH_PREFIX: release-prepare/v
  YAOOK_K8S_RELEASE_HOTFIX_BRANCH_PREFIX: hotfix/
  YAOOK_K8S_DEFAULT_BRANCH: devel

  REGEX_RELEASE_BRANCH_PREFIX: /^release\/v\S+$/
  REGEX_RELEASE_PREPARE_BRANCH_PREFIX: /^release-prepare\/v\S+$/
  REGEX_RELEASE_HOTFIX_BRANCH_PREFIX: /^hotfix\/\S+$/
  REGEX_RELEASE_HOTFIX_BASE_BRANCH_PREFIX: /^hotfix\/base\S+$/

  YAOOK_K8S_CI_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/ci
  YAOOK_K8S_CI_IMAGE_TAG:
    description: "The container image tag that should be used for this pipeline"
  SKIP_HOUSEKEEPING:
    description: "Whether the housekeeping stage should be skipped in this pipeline"
    value: "false"
    options:
    - "false"
    - "true"
  SKIP_LINT:
    description: "Whether the lint stage should be skipped in this pipeline"
    value: "false"
    options:
    - "false"
    - "true"

# Pipelines run on devel branch, release-(prepare)-branches and merge requests
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $YAOOK_K8S_DEFAULT_BRANCH
    - if: '$CI_COMMIT_BRANCH =~ $REGEX_RELEASE_PREPARE_BRANCH_PREFIX'
    - if: '$CI_COMMIT_BRANCH =~ $REGEX_RELEASE_BRANCH_PREFIX'
    - if: $CI_MERGE_REQUEST_EVENT_TYPE
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
- build-image  # needs to run first (see !1627)
- housekeeping
- lint
- unit-tests
- hotfix-prepare
- cluster-tests
- diagnostic-tools
- tag-image
- release

include:
  - local: ci/stages/build-image.yaml
  - local: ci/stages/housekeeping.yaml
  - local: ci/stages/lint.yaml
  - local: ci/stages/unit-tests.yaml
  - local: ci/stages/hotfix-prepare.yaml
  - local: ci/stages/cluster-tests.yaml
  - local: ci/stages/diagnostic-tools.yaml
  - local: ci/stages/tag-image.yaml
  - local: ci/stages/release.yaml
