---
- name: Determine pod limit to use for master nodes
  set_fact:
    kubelet_pod_limit: "{{ k8s_kubelet_pod_limit_master }}"
  when: "'masters' in group_names"

- name: Determine pod limit to use for worker nodes
  set_fact:
    kubelet_pod_limit: "{{ k8s_kubelet_pod_limit_worker }}"
  when: "'workers' in group_names"

- name: Configure and restart kubelet
  when: >
    ( _allow_disruption | default(False)
        or do_upgrade | default(False)
        or _init_cluster | default(False))
  become: true
  block:
  - name: Set the maximum number of Pods
    lineinfile:
      path: /var/lib/kubelet/config.yaml
      regexp: 'maxPods:(\s+)([0-9]+)(\s*)\n?$'
      line: "maxPods: {{ kubelet_pod_limit }}"
      state: present
      owner: root
      group: root
      mode: 0600
    notify: restart kubelet

  - name: Patch kubelet config for eviction values
    when: "'workers' in group_names"
    block:
    - name: Slurp current kubelet config
      slurp:
        src: /var/lib/kubelet/config.yaml
      register: kubelet_config
    - name: Patch kubelet config for eviction values
      vars:
        eviction_values:
          evictionSoft:
            memory.available: "384Mi"
          evictionSoftGracePeriod:
            memory.available: "{{ k8s_kubelet_evictionsoft_memory_period }}"
          evictionHard:
            memory.available: "256Mi"
            nodefs.available: "{{ k8s_kubelet_evictionhard_nodefs_available }}"
            imagefs.available: "15%"
            nodefs.inodesFree: "{{ k8s_kubelet_evictionhard_nodefs_inodesfree }}"
      copy:
        content: "{{ (kubelet_config.content | b64decode | from_yaml) | combine(eviction_values) | to_nice_yaml }}"
        dest: /var/lib/kubelet/config.yaml
        owner: root
        group: root
        mode: 0600
      notify: restart kubelet

- name: Force restart of kubelet if requested
  debug:
    msg: It IS requested!
  changed_when: true
  notify: restart kubelet
  when: _require_kubelet_restart | default(False)

- name: Flush handlers
  meta: flush_handlers
...
