---
- name: Add Kubernetes community-owned repository (apt)
  become: true
  block:
    - name: Ensure keyrings directory exists
      # ftr: this is present by default on Debian...
      file:
        state: directory
        path: /etc/apt/keyrings
        owner: root
        group: root
        mode: u=rwx,go=rx

    - name: Deploy Kubernetes community-owned repository key
      copy:
        src: apt-key.gpg
        dest: /etc/apt/keyrings/kubeadm.gpg
        owner: root
        group: root
        mode: u=rw,go=r

    - name: Drop deprecated Google's K8s repository
      become: true
      file:
        path: /etc/apt/sources.list.d/kubernetes.list
        state: absent
      register: drop_google_repo

    - name: Add Kubernetes community-owned repository to sources.list
      vars:
        # If "next_k8s_version" is set, we assume we're in the Kubernetes upgrade procedure.
        # In that case, we want to switch to the next version.
        repo_version: '{{ next_k8s_version | default(k8s_version) | regex_replace("^v?(\d+\.\d+)(\.\d+)?$", "\1") }}'
      copy:
        dest: /etc/apt/sources.list.d/kubernetes-community.list
        content: |
          {{ _auto_generated_preamble }}
          {% if apt_proxy_url is not none %}
          deb [signed-by=/etc/apt/keyrings/kubeadm.gpg] http://pkgs.k8s.io/core:/stable:/v{{ repo_version }}/deb/ /
          {% else %}
          deb [signed-by=/etc/apt/keyrings/kubeadm.gpg] https://pkgs.k8s.io/core:/stable:/v{{ repo_version }}/deb/ /
          {% endif %}
        owner: root
        group: root
        mode: 0640

    - name: Update apt cache
      # Note: check available version with `apt-cache policy <package name>`
      apt:
        update_cache: true
      register: task_result
      until: task_result is not failed
      retries: "{{ error_retries }}"
      delay: "{{ error_delay }}"
...
