---
- name: Get current kubelet-config ConfigMap
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    name: kubelet-config
    namespace: kube-system
  register: kubelet_configmap
  until: kubelet_configmap is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"

# The CloudDualStackNodeIPs feature gate went GA with Kubernetes v1.32
# which means it must be removed from the kubelet config (as it is always enabled now).
# Otherwise kubelet complains and refuses to run.
# Drop me along with Kubernetes v1.31
- name: Remove CloudDualStackNodeIPs feature gate from kubelet-config ConfigMap
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: kubelet-config
        namespace: kube-system
      data:
        kubelet: "{{ kubelet_configmap.resources[0].data.kubelet | from_yaml | ansible.utils.remove_keys(target=['CloudDualStackNodeIPs']) | to_nice_yaml(indent=2) }}"
  register: kubelet_configmap_patched
  until: kubelet_configmap_patched is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"
...
