---
- name: Create namespace for fluxcd
  kubernetes.core.k8s:
    apply: true
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ fluxcd_namespace }}"
        labels:
          app.kubernetes.io/instance: flux-system
          app.kubernetes.io/part-of: flux
          pod-security.kubernetes.io/warn: restricted
          pod-security.kubernetes.io/warn-version: latest
    validate:
      fail_on_error: true
      strict: true
  # Retry this task on failures
  register: k8s_apply
  until: k8s_apply is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"

- name: Install fluxcdv2
  vars:
    scheduling_key: "{{ fluxcd_scheduling_key | default(None) }}"
  kubernetes.core.helm:
    chart_repo_url: "{{ fluxcd_helm_repo_url }}"
    chart_ref: flux2
    release_namespace: "{{ fluxcd_namespace }}"
    release_name: flux2
    release_state: "{{ fluxcd_install | ternary('present', 'absent') }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    chart_version: "{{ fluxcd_version }}"
...
