---
- name: kubeadm upgrade plan & apply
  become: true
  when: do_upgrade | bool
  block:
    - name: Upload kubeadm-upgrade-config.yaml
      copy:
        src: "{{ k8s_kubeadm_upgradeConfigurations[inventory_hostname] }}"
        dest: /tmp/kubeadm-upgrade-config.yaml
        owner: root
        group: root
        mode: 0600

    - name: Run kubeadm upgrade plan  # noqa no-changed-when
      vars:
        kubeadm_expression:
          - "kubeadm"
          - "upgrade"
          - "plan"
          - "v{{ next_k8s_version }}"
          - "--ignore-preflight-errors=CreateJob" # timeout is hardcoded to 15s, so we ignore errors
          # NOTE: --config=/tmp/kubeadm-upgrade-config.yaml can't be used here
          #       because `kubernetesVersion` (next_k8s_version) is currently not known
          #       when the configuration is rendered but required to be specified
      include_role:
        name: helpers/kubeadm-command

    # --yes auto-confirms and makes upgrade non-interactive
    - name: Execute the upgrade
      vars:
        kubeadm_expression:
          - "kubeadm"
          - "upgrade"
          - "apply"
          - "v{{ next_k8s_version }}"
          - "--yes"
          - "--config=/tmp/kubeadm-upgrade-config.yaml"
      include_role:
        name: helpers/kubeadm-command

    - name: Remove kubeadm-upgrade-config.yaml
      file:
        path: /tmp/kubeadm-upgrade-config.yaml
        state: absent

# Running kubeadm upgrade apply potentially resets
# the KubeletConfiguration on the node
# We have to reconfigure it before continuing therefore
- name: Configure and restart kubelet
  include_role:
    name: kubelet-configuration
...

