---
- name: Sanity check
  assert:
    that:
    - kubeadm_expression is sequence
    - kubeadm_expression is not mapping
    - kubeadm_expression is iterable
    - kubeadm_expression is not string
    - kubeadm_expression | first == "kubeadm"
    fail_msg: |
      The following does not look like a proper list of a kubeadm command:
      "{{ kubeadm_expression | to_nice_yaml }}"

- name: Run kubeadm command on worker node
  become: true
  when: "'workers' in group_names"
  block:
  - name: "Running '{{ kubeadm_expression | map('quote') | join(' ') }}' on worker"  # noqa no-changed-when
    shell: "umask 077 && {{ kubeadm_expression | map('quote') | join(' ') }}"
    async: 1800
    poll: 3

- name: Run kubeadm command on control plane node
  become: true
  when: "'masters' in group_names"
  block:
  - include_tasks: hide-ca-key.yaml
  - block:
    - name: "Running '{{ kubeadm_expression | map('quote') | join(' ') }}' on control plane node"  # noqa no-changed-when
      shell: "umask 077 && {{ kubeadm_expression | map('quote') | join(' ') }}"
      async: 1800
      poll: 3
      register: kubeadm_command
    always:
    - include_tasks: reveal-ca-key.yaml
    - name: Fail if kubeadm command failed
      when: kubeadm_command.rc != 0
      fail:
        msg: |
          Running '{{ kubeadm_expression | map('quote') | join(' ') }}' failed with the following output:

          {{ kubeadm_command.stderr }}
...
