---
- name: Install Nvidia Device Plugin
  delegate_to: "{{ groups['orchestrator'] | first }}"
  run_once: true
  block:
  - name: "{{ nvidia_device_plugin_install | ternary('Create', 'Delete') }} namespace"
    kubernetes.core.k8s:
      apply: true
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{ nvidia_device_plugin_helm_release_namespace }}"
      state: "{{ nvidia_device_plugin_install | ternary('present', 'absent') }}"
      validate:
        fail_on_error: true
        strict: true
    # Retry this task on failures
    register: k8s_apply
    until: k8s_apply is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

  - name: "{{ nvidia_device_plugin_install | ternary('Install', 'Uninstall') }} nvidia-device-plugin"
    kubernetes.core.helm:
      chart_repo_url: "{{ nvidia_device_plugin_helm_chart_repo_url }}"
      chart_ref: "{{ nvidia_device_plugin_helm_chart_ref }}"
      chart_version: "{{ nvidia_device_plugin_helm_chart_version }}"
      release_namespace: "{{ nvidia_device_plugin_helm_release_namespace }}"
      release_name: "{{ nvidia_device_plugin_helm_release_name }}"
      release_state: "{{ nvidia_device_plugin_install | ternary('present', 'absent') }}"
      values: "{{ nvidia_device_plugin_helm_values }}"
...
