{
  lib,
  pkgs,
  ...
}: rec {
  options = import ./options.nix {inherit lib;};
  types = import ./types {inherit lib;};
  transform = import ./transform.nix {inherit lib;};
  k8s = import ./k8s.nix {inherit lib;};

  inherit
    (options)
    mkDisableOption
    mkInternalOption
    mkOptional
    mkTopSection
    mkSubSection
    ;

  inherit (transform) removeAttrByPath removeAttrsByPath;

  withAutoGeneratedPreamble = let
    preamble = builtins.toFile "auto_generated_preamble.txt" ''
      ###########################################################
      # This file is automatically generated by Tarook.         #
      # Do not modify this file -- YOUR CHANGES WILL BE ERASED! #
      ###########################################################
    '';
  in
    name: file:
      pkgs.runCommandLocal name {} ''
        cat ${preamble} ${file} > $out
      '';

  # Generates a Terraform/OpenTofu ressource reference with proper escaping
  tfRef = ref: "\${${ref}}";

  mkGroupVarsFile = {
    cfg,
    inventory_path,
    ansible_prefix ? "",
    only_if_enabled ? false,
    transformations ? [],
    unflat ? [],
  }: let
    inherit (lib.trivial) pipe;
    inherit (pkgs.stdenv) mkDerivation;
    path = "group_vars/${inventory_path}";
    finalConfig = let
      t = transform;
    in
      pipe cfg (
        (lib.optional only_if_enabled t.onlyIfEnabled)
        ++ [
          t.removeObsoleteOptions
          t.filterInternal
        ]
        ++ cfg._internal.transformations or []
        ++ transformations
        ++ [
          (t.flatten {except = (cfg._internal.unflat or []) ++ unflat;})
          (t.addPrefix ansible_prefix)
        ]
      );
  in
    builtins.traceVerbose "Writing file: ${path}" (mkYamlAtPath path finalConfig);
  mkYamlBundle = name: docs: (pkgs.runCommandLocal name {
      nativeBuildInputs = [pkgs.jq pkgs.yq];
      valueStream = lib.concatStrings (lib.map (v: builtins.toJSON v) docs);
      passAsFile = ["valueStream"];
    } ''
      echo > "$out"
      jq --compact-output . "$valueStreamPath" \
        | while IFS= read -r line; do
          yq \
            --yaml-output \
            --explicit-start --explicit-end \
            --indentless-lists \
            . <<<"$line" >> "$out"
        done
    '');
  mkYaml = name: attrs:
    withAutoGeneratedPreamble name
    (pkgs.runCommandLocal name {
        nativeBuildInputs = [pkgs.yq];
        value = builtins.toJSON attrs;
        passAsFile = ["value"];
      } ''
        yq --yaml-output --indentless-lists . "$valuePath" > "$out"
      '');
  mkYamlAtPath = path: attrs: linkToPath (mkYaml path attrs) path;
  mkJson = name: attrs:
    pkgs.runCommandLocal name {
      value = builtins.toJSON attrs;
      passAsFile = ["value"];
    } ''
      cp "$valuePath" "$out"
    '';
  mkJsonAtPath = path: attrs: linkToPath (mkJson path attrs) path;
  linkToPath = file: path:
    pkgs.runCommandLocal path {
    } ''
      mkdir -p $(dirname $out/${path})
      ln -s ${file} $out/${path}
    '';

  baseSystemAssertWarn = {
    assertions,
    warnings,
    ...
  }: let
    inherit (builtins) map filter concatStringsSep trace;
    inherit (lib) showWarnings;
    failedAssertions = map (x: x.message) (filter (x: !x.assertion) assertions);
  in
    if failedAssertions != []
    then throw "\nFailed assertions:\n${concatStringsSep "\n" (map (x: "- ${x}") failedAssertions)}"
    else showWarnings warnings "";

  importTOML = file: fromTOML (builtins.readFile file);
  importYAML = file: let
    jsonFile = pkgs.runCommandLocal "converted-yaml.json" {} ''
      ${pkgs.yj}/bin/yj < "${file}" > "$out"
    '';
  in
    builtins.fromJSON (builtins.readFile jsonFile);
  importYAMLTree = dir: (lib.attrsets.mapAttrs' (file: _: {
    name = lib.strings.removeSuffix ".yaml" file;
    value = importYAML "${dir}/${file}";
  }) (builtins.readDir dir));

  isValidSemver2 = transform.matchesRegex types.yk8s.version._regexes.semver.v2.versionStrRE;
}
