---
- name: Run kubeadm upgrade node on CP node  # noqa no-changed-when
  when:
    - do_upgrade | bool
    - "'masters' in group_names"
  vars:
    kubeadm_expression:
      - "kubeadm"
      - "upgrade"
      - "node"
      - "--patches"
      - "/etc/kubernetes/kubeadm-patches"
      - "--certificate-renewal=false"
  include_role:
    name: helpers/kubeadm-command

- name: Run kubeadm upgrade node on worker node  # noqa no-changed-when
  when:
    - do_upgrade | bool
    - "'workers' in group_names"
  vars:
    kubeadm_expression:
      - "kubeadm"
      - "upgrade"
      - "node"
  include_role:
    name: helpers/kubeadm-command

# Running kubeadm upgrade node potentially resets
# the KubeletConfiguration on the node
# We have to reconfigure it before continuing therefore
- name: Configure and restart kubelet
  include_role:
    name: kubelet-configuration
...
