---
- name: Figure out kubeadm version  # noqa no-changed-when
  command:
    argv:
    - kubeadm
    - version
    - -o=json
  register: kubeadm_version

- name: Patch kubeadm ConfigMap
  delegate_to: "{{ groups['orchestrator'] | first }}"
  run_once: true
  block:
  - name: Get current ConfigMap
    kubernetes.core.k8s_info:
      api_version: v1
      kind: ConfigMap
      name: kubeadm-config
      namespace: kube-system
    register: kubeadm_configmap
    until: kubeadm_configmap is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

  # kubeadm uses v1beta4 since v1.31
  # the type of etcd.local.extraArgs changed in-between
  # https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta4/
  - name: Patch kubeadm-config ConfigMap (>= K8s v1.31)
    when: (kubeadm_version.stdout | from_json).clientVersion.minor | int >= 31
    vars:
      current_cluster_configuration: "{{ kubeadm_configmap.resources[0].data.ClusterConfiguration | from_yaml }}"
      patch:
        etcd:
          local:
            extraArgs:
            - name: listen-metrics-urls
              value: "http://127.0.0.1:2381,http://[::1]:2381"
    kubernetes.core.k8s:
      definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: kubeadm-config
          namespace: kube-system
        data:
          ClusterConfiguration: "{{ current_cluster_configuration | combine(patch, recursive=true) | to_nice_yaml(indent=2) }}"
    register: kubeadm_configmap_patched
    until: kubeadm_configmap_patched is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

  - name: Patch kubeadm-config ConfigMap (< K8s v1.31)
    when: (kubeadm_version.stdout | from_json).clientVersion.minor | int < 31
    vars:
      current_cluster_configuration: "{{ kubeadm_configmap.resources[0].data.ClusterConfiguration | from_yaml }}"
      patch:
        etcd:
          local:
            extraArgs:
              listen-metrics-urls: "http://127.0.0.1:2381,http://[::1]:2381"
    kubernetes.core.k8s:
      definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: kubeadm-config
          namespace: kube-system
        data:
          ClusterConfiguration: "{{ current_cluster_configuration | combine(patch, recursive=true) | to_nice_yaml(indent=2) }}"
    register: kubeadm_configmap_patched
    until: kubeadm_configmap_patched is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

- name: Regenerate etcd manifests
  become: true
  block:
  - name: Get current ConfigMap
    become: false
    delegate_to: "{{ groups['orchestrator'] | first }}"
    kubernetes.core.k8s_info:
      api_version: v1
      kind: ConfigMap
      name: kubeadm-config
      namespace: kube-system
    register: kubeadm_configmap
    until: kubeadm_configmap is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

  - name: Create ClusterConfiguration file
    copy:
      dest: /tmp/cluster-configuration.yaml
      owner: root
      group: root
      mode: 0400
      content: "{{ kubeadm_configmap.resources[0].data.ClusterConfiguration }}"

  # needed for kubeadm init
  - name: Generate super admin kubeconfig
    become: false
    environment:
      ANSIBLE_HASHI_VAULT_URL: "{{ lookup('env', 'VAULT_ADDR') }}"
      ANSIBLE_HASHI_VAULT_CA_CERT: "{{ lookup('env', 'VAULT_CACERT') }}"
    # must use block to be able to set environment
    block:
    - name: Generate super admin kubeconfig
      include_role:
        name: k8s-master
        tasks_from: mkkubeconfig.yaml
      vars:
        kubeconfig_api_server_url: "https://{% if ipv4_enabled %}{{ networking_fixed_ip }}{% elif ipv6_enabled %}[{{ networking_fixed_ip_v6 }}]{% endif %}:{{ k8s_apiserver_frontend_port }}"
        vault_role_id: "{{ vault_node_role_id }}"
        vault_secret_id: "{{ vault_node_secret_id }}"
        kubeconfig_title: super-admin
        kubeconfig_destination: /etc/kubernetes/super-admin.conf
        kubeconfig_role: system-masters_admin
        kubeconfig_user: kubernetes-super-admin

  - name: Regenerate etcd manifest via kubeadm  # noqa no-changed-when
    vars:
      kubeadm_expression:
      - kubeadm
      - init
      - phase
      - etcd
      - local
      - --config
      - /tmp/cluster-configuration.yaml
    include_role:
      name: helpers/kubeadm-command

  - name: Remove super admin kubeconfig
    file:
      path: /etc/kubernetes/super-admin.conf
      state: absent

  - name: Remove ClusterConfiguration file
    file:
      path: /tmp/cluster-configuration.yaml
      state: absent
...
