---
- name: "{{ (gpu_nodes.resources | length > 0) | ternary('I', 'Uni') }}nstall NVIDIA DCGM exporter"
  kubernetes.core.helm:
    chart_ref: "{{ monitoring_nvidia_dcgm_exporter_helm_chart_ref }}"
    chart_repo_url: "{{ monitoring_nvidia_dcgm_exporter_helm_chart_repo_url }}"
    chart_version: "{{ monitoring_nvidia_dcgm_exporter_helm_chart_version }}"
    release_namespace: "{{ monitoring_nvidia_dcgm_exporter_helm_release_namespace }}"
    release_name: "{{ monitoring_nvidia_dcgm_exporter_helm_release_name }}"
    release_state: "{{ (gpu_nodes.resources | length > 0) | ternary('present', 'absent') }}"
    values: "{{ monitoring_nvidia_dcgm_exporter_helm_values | to_json }}"
    wait: true
...
