---
- name: Check that calico/node and typha Pods are running
  delegate_to: "{{ groups['orchestrator'] | first }}"
  run_once: true
  block:
  - name: Check running and readiness status of the tigera operator
    kubernetes.core.k8s_info:
      kind: Pod
      label_selectors:
      - k8s-app=tigera-operator
    register: pod_info
    until:
    - (pod_info.resources[0].status.phase | default("")) == "Running"
    - (pod_info.resources[0].status.containerStatuses[0].ready | default(False)) | bool
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

  - name: Check running and readiness status of calico pods
    kubernetes.core.k8s_info:
      kind: Pod
      label_selectors:
      - app.kubernetes.io/name={{ item }}
    register: pod_info
    until:
    - (pod_info.resources[0].status.phase | default("")) == "Running"
    - (pod_info.resources[0].status.containerStatuses[0].ready | default(False)) | bool
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"
    with_items:
    - calico-node
    - calico-typha
    - calico-apiserver
    - calico-kube-controllers
...
