---
- name: Check if tigera-operator already exists
  delegate_to: "{{ groups['orchestrator'] | first }}"
  run_once: true
  block:
    - name: Check if tigera-operator Deployment exists
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Deployment
        name: tigera-operator
        namespace: tigera-operator
      register: tigera_operator_deployment

    - name: Set fact if tigera-operator Deployment exists
      set_fact:
        tigera_operator_exists: "{{ tigera_operator_deployment.resources | length >= 1 | bool }}"

# Always applying if Tigera operator already exists
# because this is faster than checking which version
# is currently deployed.
# Drop me along with support for Kubernetes v1.30
- name: Deploy CRDs for Calico v3.29
  when:
    - image_versions.calico_version is version('3.29', 'ge')
    - image_versions.calico_version is version('3.30', 'lt')
    - tigera_operator_exists
  delegate_to: "{{ groups['orchestrator'] | first }}"
  run_once: true
  kubernetes.core.k8s:
    definition: "{{ lookup('file', 'v3.29-operator-crds.yaml') }}"
    apply: true
    state: present
    server_side_apply:
      force_conflicts: true
      field_manager: ansible
    validate:
      fail_on_error: true
      strict: true
  # Retry this task on failures
  register: k8s_apply
  until: k8s_apply is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"

# Always applying if Tigera operator already exists
# because this is faster than checking which version
# is currently deployed.
# Drop me along with support for Kubernetes v1.31
- name: Deploy CRDs for Calico v3.30
  when:
    - image_versions.calico_version is version('3.30', 'ge')
    - image_versions.calico_version is version('3.31', 'lt')
    - tigera_operator_exists
  delegate_to: "{{ groups['orchestrator'] | first }}"
  run_once: true
  kubernetes.core.k8s:
    definition: "{{ lookup('file', 'v3.30-operator-crds.yaml') }}"
    apply: true
    state: present
    server_side_apply:
      force_conflicts: true
      field_manager: ansible
    validate:
      fail_on_error: true
      strict: true
  # Retry this task on failures
  register: k8s_apply
  until: k8s_apply is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"

- name: Deploy tigera-operator
  delegate_to: "{{ groups['orchestrator'] | first }}"
  run_once: true
  block:
    - name: Create Tigera operator namespace
      kubernetes.core.k8s:
        apply: true
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: tigera-operator
        validate:
          fail_on_error: true
          strict: true
      # Retry this task on failures
      register: k8s_apply
      until: k8s_apply is not failed
      retries: "{{ error_retries }}"
      delay: "{{ error_delay }}"

    - name: Deploy Tigera operator chart
      kubernetes.core.helm:
        chart_repo_url: "{{ calico_helm_repo_url }}"
        chart_ref: tigera-operator
        chart_version: "{{ image_versions.calico_version }}"
        release_namespace: "tigera-operator"
        release_name: "calico"
        release_state: present
        values: "{{ lookup('template', calico_values_file_path) | from_yaml }}"

    # Give the operator some time to create the CRDs
    - name: Pause for 20s
      when: not tigera_operator_exists
      pause:
        seconds: 20

- name: Install calicoctl
  become: true
  get_url:
    url: "{{ calico_calicoctl_binary_source }}/v{{ image_versions.calico_version }}/calicoctl-linux-amd64"
    dest: /usr/local/bin/calicoctl
    owner: root
    group: root
    mode: 0750
    timeout: 30
  register: task_result
  until: task_result is not failed
  retries: "{{ error_retries }}"

- name: Setup BGP Routing Information Distribution via BIRD
  run_once: true
  include_tasks: setup_bgp.yaml
...
