---
- name: Uncordon the worker node
  delegate_to: "{{ groups['orchestrator'] | first }}"
  retries: 5
  delay: 10
  when: _allow_disruption
  command:
  args:
    argv:
    - kubectl
    - uncordon
    - "{{ inventory_hostname }}"
  register: uncordon_result
  until: uncordon_result is successful
  changed_when: "'uncordoned' in uncordon_result.stdout"
- name: Include post-uncordon hooks
  include_role:
    name: '{{ item }}'
  loop: '{{ hooks_post_uncordon_roles }}'
...
