---
- name: Install GPU drivers
  become: true
  when: ansible_local['gpu-node']['node_has_gpu'] | bool
  block:
  # https://docs.nvidia.com/datacenter/cloud-native/kubernetes/k8s-containerd.html#disable-nouveau
  - name: Blacklist Nouveau driver
    copy:
      dest: /etc/modprobe.d/blacklist_nouveau.conf
      content: |
        {{ _auto_generated_preamble }}
        blacklist nouveau
        options nouveau modeset=0
      mode: 0755
      owner: root
      group: root
    register: blacklisted_nouveau

  - name: Install deps for the nvidia drivers
    apt:
      state: present
      name:
      - "linux-headers-{{ ansible_kernel }}"
      - gcc
    register: task_result
    until: task_result is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

  - name: Ensure keyrings directory exists
    # ftr: this is present by default on Debian...
    file:
      state: directory
      path: /etc/apt/keyrings
      owner: root
      group: root
      mode: u=rwx,go=rx

  - name: Deploy nvidia cuda driver repository key
    copy:
      src: nvidia-cuda-driver.gpg
      dest: /etc/apt/keyrings/nvidia-cuda-driver.gpg
      owner: root
      group: root
      mode: u=rw,go=r

  - name: Add nvidia cuda repository
    vars:
      distribution_string: "{{ '%s%s' | format(ansible_distribution | lower, ansible_distribution_version | replace('.', '')) }}"
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/nvidia-cuda-driver.gpg] https://developer.download.nvidia.com/compute/cuda/repos/{{ distribution_string }}/x86_64/ /"
      state: present
      update_cache: true
    register: task_result
    until: task_result is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

  # We must install a supported version for datacenters
  # https://docs.nvidia.com/datacenter/tesla/drivers/latest/supported-drivers-and-cuda-toolkit-versions.html
  - name: Install nvidia cuda drivers
    apt:
      update_cache: false  # this is done in the task before
      install_recommends: false
      autoremove: true
      allow_change_held_packages: true
      name:
      - nvidia-headless-595
      - nvidia-utils-595

    register: installed_driver
    until: installed_driver is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

  - name: Prevent the cuda-drivers from being updated automatically  # noqa no-changed-when
    command: apt-mark hold nvidia-utils-595 nvidia-headless-595

  - name: Update initramfs  # noqa no-changed-when no-handler
    command: "update-initramfs -k {{ ansible_kernel }} -uv"
    when: blacklisted_nouveau.changed or installed_driver.changed
    register: ramfs

  - name: Reboot block (gpu)  # noqa no-handler
    when: ramfs.changed
    block:
    - name: Reboot the system  # noqa no-changed-when
      command:
        argv:
        - reboot
        - now
      when: ansible_connection == 'local'
      retries: "{{ error_retries }}"
      delay: "{{ error_delay }}"

    - name: Reboot the system
      reboot:
...
