---
- name: Initialize Snapshots
  vars:
    # TODO: Track this version via Renovate Bot
    files_folder: 'v8.4.0/'
  block:
  - name: Create Custom Snapshot Resource Definitions
    kubernetes.core.k8s:
      definition: "{{ lookup('file', files_folder + 'crds/' + item) }}"
      apply: true
      state: present
      validate:
        fail_on_error: true
        strict: true
    loop:
    - "snapshot.storage.k8s.io_volumesnapshots.yaml"
    - "snapshot.storage.k8s.io_volumesnapshotcontents.yaml"
    - "snapshot.storage.k8s.io_volumesnapshotclasses.yaml"
    # Retry this task on failures
    register: k8s_apply
    until: k8s_apply is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

  - name: Deploy the Snapshot Controller and its RBAC
    kubernetes.core.k8s:
      state: present
      apply: true
      definition: "{{ lookup('file', files_folder + 'snapshot-controller/' + item) }}"
      validate:
        fail_on_error: true
        strict: true
    loop:
    - rbac-snapshot-controller.yaml
    - setup-snapshot-controller.yaml
    # Retry this task on failures
    register: k8s_apply
    until: k8s_apply is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"
...
