---
# For helm charts of Bitnami the OCI format must be used
# https://community.broadcom.com/tanzu/blogs/carlos-rodriguez-hernandez/2025/01/14/bitnami-helm-charts-moving-to-oci
monitoring_thanos_helm_oci_url: "oci://registry-1.docker.io/bitnamicharts"
monitoring_thanos_chart_ref: "thanos"
monitoring_thanos_release_name: "thanos"

monitoring_thanos_config_secret_name: "thanos-bucket-config"

monitoring_thanos_retention_resolution_raw: "30d"
monitoring_thanos_retention_resolution_5m: "60d"
monitoring_thanos_retention_resolution_1h: "180d"

monitoring_common_labels: {}
...
