---
- name: Install wireguard
  become: true
  apt:
    state: present
    name:
    - wireguard
  register: task_result
  until: task_result is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"

- name: Modprobe the wireguard module to ensure its existence
  become: true
  community.general.modprobe:
    name: wireguard
    state: present
...
