---
- name: Install ch-k8s-lbaas-agent
  when: ch_k8s_lbaas_enabled
  include_tasks: install.yaml

- name: Uninstall ch-k8s-lbaas-agent
  when: not ch_k8s_lbaas_enabled
  include_tasks: uninstall.yaml
...
