---
- name: Read role-id
  become: true
  # We cannot use a lookup('file', ..) here, because lookup is executed
  # locally. We need to read the role-id and secret-id from the potentially
  # remote node though.
  command:
  args:
    argv:
    - cat
    - /etc/vault/role-id
  register: cat_role_id
  changed_when: false
  tags: always

- name: Discover current on-node secret ids
  become: true
  find:
    paths: "/etc/vault/"
    patterns: "secret-id-*"
    use_regex: true
    file_type: "file"
    recurse: false
  register: find_secret_id_files

- name: Read secret-ids
  become: true
  # We cannot use a lookup('file', ..) here, because lookup is executed
  # locally. We need to read the role-id and secret-ids from the potentially
  # remote node though.
  command:
  args:
    argv:
    - cat
    - "{{ item }}"
  with_items: "{{ find_secret_id_files.files | map(attribute='path') }}"
  register: cat_secret_ids
  changed_when: false
  tags: always

- name: Set credentials
  set_fact:
    vault_node_role_id: "{{ cat_role_id.stdout }}"
    # Build a mapping of secret id file suffix (equals a vault cluster name) to secret id file content
    vault_node_secret_ids: >
      {{
        dict(
          (cat_secret_ids.results | map(attribute='item') | map('basename') | map('regex_replace', '^secret-id-', ''))
          | zip(cat_secret_ids.results | map(attribute='stdout'))
        )
      }}
  tags: always
