---
- name: Install nvidia-container-toolkit
  become: true
  when:
  - ansible_local['gpu-node']['node_has_gpu'] | bool
  - |
    ((ansible_local['kubernetes-initialized']['k8s_install_status'] | default('not_initialized')) != 'initialized')
    or (_allow_disruption | bool)
  block:
  - name: Ensure keyrings directory exists
    file:
      state: directory
      path: "/etc/apt/keyrings"
      owner: root
      group: root
      mode: u=rwx,go=rx

  - name: Deploy libnvidia-container repository key to keyrings
    copy:
      src: libnvidia-container.gpg
      dest: /etc/apt/keyrings/libnvidia-container.gpg
      owner: root
      group: root
      mode: u=rw,go=r

  - name: Add libnvidia-container repository
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/libnvidia-container.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /"
      state: present
      filename: nvidia-container-toolkit
      update_cache: true
    register: task_result
    until: task_result is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

  - name: Install nvidia-container-toolkit package
    apt:
      update_cache: false  # this is done in the task before
      install_recommends: false
      autoremove: true
      allow_change_held_packages: true
      name:
      - nvidia-container-toolkit
      - nvidia-container-toolkit-base
      - libnvidia-container-tools
      - libnvidia-container1
    register: nvidia_container_toolkit_pkg
    until: nvidia_container_toolkit_pkg is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

  - name: Reduce nvidia-container-runtime log level # noqa no-changed-when
    command:
    args:
      argv:
      - nvidia-ctk
      - config
      - "--set"
      - "nvidia-container-runtime.log-level=error"
      - "--in-place"
    register: nvidia_container_toolkit_level
    until: nvidia_container_toolkit_level is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

  - name: Prevent the cuda-drivers from being updated automatically  # noqa no-changed-when
    command: apt-mark hold nvidia-container-toolkit nvidia-container-toolkit-base libnvidia-container-tools libnvidia-container1
...
