---
- name: Create cloud-config secret
  kubernetes.core.k8s:
    apply: true
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      data:
        cloud.conf: "{{ lookup('template', 'os_cloud_config.ini.j2') | b64encode }}"
      metadata:
        name: cloud-config
        namespace: kube-system
    validate:
      fail_on_error: true
      strict: true
  notify:
  - restart CCM
  - restart csi-cinder-controllerplugin
  - restart openstack-cinder-csi-nodeplugin
  # Retry this task on failures
  register: k8s_apply
  until: k8s_apply is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"

- name: Start the OpenStack Cloud Controller manager
  block:
  - name: Deploy Cloud-Controller-Manager chart
    kubernetes.core.helm:
      chart_repo_url: "{{ openstack_cloud_controller_manager_helm_chart_repo_url }}"
      chart_ref: "{{ openstack_cloud_controller_manager_helm_chart_ref }}"
      chart_version: "{{ openstack_cloud_controller_manager_helm_chart_version }}"
      release_namespace: "{{ openstack_cloud_controller_manager_helm_release_namespace }}"
      release_name: "{{ openstack_cloud_controller_manager_helm_release_name }}"
      release_state: present
      values: "{{ openstack_cloud_controller_manager_helm_values | to_json }}"
      wait: true
    notify:
    - restart CCM
    - restart csi-cinder-controllerplugin
    - restart openstack-cinder-csi-nodeplugin

  - name: Deploy Cinder CSI driver plugin chart
    kubernetes.core.helm:
      chart_repo_url: "{{ openstack_cinder_helm_chart_repo_url }}"
      chart_ref: "{{ openstack_cinder_helm_chart_ref }}"
      chart_version: "{{ openstack_cinder_helm_chart_version }}"
      release_namespace: "{{ openstack_cinder_helm_release_namespace }}"
      release_name: "{{ openstack_cinder_helm_release_name }}"
      release_state: present
      values: "{{ openstack_cinder_helm_values | to_json }}"
      wait: false

  - name: Create cinder storage class (hdd)
    kubernetes.core.k8s:
      state: present
      apply: true
      definition: "{{ lookup('template', 'cinder_storage_class.yaml.j2') }}"
      validate:
        fail_on_error: true
        strict: true
    # Retry this task on failures
    register: k8s_apply
    until: k8s_apply is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

  - name: Create cinder storage class (nvme)
    when: openstack_cinder_nvme | bool
    kubernetes.core.k8s:
      state: present
      apply: true
      definition: "{{ lookup('file', 'cinder/cinder_nvme_storage_class.yaml') }}"
      validate:
        fail_on_error: true
        strict: true
    # Retry this task on failures
    register: k8s_apply
    until: k8s_apply is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

  - name: Create volume snapshot class (hdd)
    kubernetes.core.k8s:
      state: present
      apply: true
      definition: "{{ lookup('file', 'cinder/volume_snapshot_storage_class.yaml') }}"
      validate:
        fail_on_error: true
        strict: true
    # Retry this task on failures
    register: k8s_apply
    until: k8s_apply is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"
...
