---
# Deploy apt repository for next_k8s_version
- name: Update the Kubernetes community-owned repository
  include_role:
    name: k8s-packages
    tasks_from: configure-package-repo.yaml

- name: Upgrade kubeadm on apt systems
  when: ansible_pkg_mgr == 'apt'
  become: true
  block:
  - name: Remove the hold of kubeadm  # noqa no-changed-when
    command: apt-mark unhold kubeadm

  - name: Upgrade kubeadm
    apt:
      name:
      - "kubeadm={{ next_k8s_version }}-*"
    register: task_result
    until: task_result is not failed
    retries: "{{ error_retries }}"
    delay: "{{ error_delay }}"

  - name: Re-hold kubeadm  # noqa no-changed-when
    command: apt-mark hold kubeadm

  - name: Check kubeadm's version  # noqa no-changed-when
    command: kubeadm version
...
