#!/bin/bash

# This script was auto-generated by ansible. Do not modify.

set -euo pipefail

#TYPE=$1
#NAME=$2
STATE=$3

case $STATE in
    "MASTER")
        /usr/bin/systemctl start wg-quick@wg-peer1
        exit 0
        ;;
    "BACKUP" | "FAULT")
        /usr/bin/systemctl stop wg-quick@wg-peer1
        exit 0
        ;;
    *)  echo "unknown state"
        exit 1
        ;;
esac
