build-users-group = nixbld
sandbox = false
extra-experimental-features = nix-command flakes
substituters = https://cache.nixos.org https://nix-cache.tarook.cloud
# pubkey for cache.nixos.org from https://github.com/NixOS/nixpkgs/blob/39fbc9ce2412372861d88946500f5f26a4188963/nixos/modules/config/nix.nix#L377
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-cache.tarook.cloud-2:2X2yPTrpwmakhSgS83FVB2fKkG6IzfOJ1AGIIcvNyM0=
