---
# Must be created before the ClusterConfiguration and kube-apiserver have been patched
- name: Upload audit log policy file
  become: true
  when: k8s_apiserver_audit_logs_enabled | bool
  copy:
    src: "{{ k8s_apiserver_audit_logs_policy_file }}"
    dest: "{{ k8s_apiserver_audit_logs_policy_remote_file }}"
    owner: root
    group: root
    mode: '0640'
  # If the policy file changed, we have to restart kube-apiserver
  notify: Restart kube-apiserver

# Skip if the node is not initialized yet, because then there is no kube-apiserver around
# In this case, the configuration is done via the kubeadm-init-config in the k8s-master role
# on cluster initializtion and joining nodes get the configuration from the kubadm ConfigMap
- name: Skip role
  when: (ansible_local['kubernetes-initialized']['k8s_install_status'] | default('not_initialized')) == 'not_initialized'
  meta: end_role

- name: Update ClusterConfiguration
  include_role:
    name: kubeadm-update-clusterconfiguration

- name: Regenerate kube-apiserver manifests
  become: true
  block:
  - name: Upload bundled kubeadm-init-config.yaml
    copy:
      src: "{{ k8s_kubeadm_initConfigurationBundles[inventory_hostname] }}"
      dest: /tmp/cluster-configuration.yaml
      owner: root
      group: root
      mode: 0600

  # needed for kubeadm init
  - name: Generate super admin kubeconfig
    become: false
    environment:
      ANSIBLE_HASHI_VAULT_URL: "{{ lookup('env', 'VAULT_ADDR') }}"
      ANSIBLE_HASHI_VAULT_CA_CERT: "{{ lookup('env', 'VAULT_CACERT') }}"
    # must use block to be able to set environment
    block:
    - name: Generate super admin kubeconfig
      include_role:
        name: k8s-master
        tasks_from: mkkubeconfig.yaml
      vars:
        kubeconfig_api_server_url: "https://{% if ipv4_enabled %}{{ networking_fixed_ip }}{% elif ipv6_enabled %}[{{ networking_fixed_ip_v6 }}]{% endif %}:{{ k8s_apiserver_frontend_port }}"
        vault_role_id: "{{ vault_node_role_id }}"
        vault_secret_id: "{{ vault_node_secret_id }}"
        kubeconfig_title: super-admin
        kubeconfig_destination: /etc/kubernetes/super-admin.conf
        kubeconfig_role: system-masters_admin
        kubeconfig_user: kubernetes-super-admin

  # Thankfully, this does only restart the kube-apiserver Pod on changes
  - name: Regenerate kube-apiserver manifest via kubeadm
    vars:
      kubeadm_expression:
      - kubeadm
      - init
      - phase
      - control-plane
      - apiserver
      - --config
      - /tmp/cluster-configuration.yaml
    include_role:
      name: helpers/kubeadm-command

  - name: Remove super admin kubeconfig
    file:
      path: /etc/kubernetes/super-admin.conf
      state: absent

  - name: Remove ClusterConfiguration file
    file:
      path: /tmp/cluster-configuration.yaml
      state: absent

# Must be removed after the ClusterConfiguration and kube-apiserver have been patched
- name: Remove audit log policy file
  become: true
  when: not (k8s_apiserver_audit_logs_enabled | bool)
  file:
    state: absent
    path: "{{ k8s_apiserver_audit_logs_policy_remote_file }}"
...
