---
# We don't want to assert mode here
- name: Create parent directories for PKI directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,go=rx
  loop:
  - /etc/kubernetes
  - /var/lib/kubelet

# The focus of the following two tasks is on fixing the permissions.
- name: Create PKI directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,go-rwx
  loop:
  - /etc/kubernetes/pki
  - /etc/kubernetes/pki/etcd
  - /var/lib/kubelet/pki

- name: Obtain CAs
  include_tasks: obtain-cas.yaml

- name: Obtain kubeconfigs
  include_tasks: obtain-kubeconfigs.yaml

- name: Join the k8s cluster steps
  when: ansible_local['kubernetes-initialized']['k8s_install_status'] | default('not_initialized') != 'initialized'
  become: true
  block:
  - name: Create kubeadm-join-config.yaml
    template:
      src: kubeadm-JoinConfiguration.yaml.j2
      dest: /tmp/kubeadm-join-config.yaml
      owner: root
      group: root
      mode: 0640

  - name: Join the k8s cluster as another worker
    vars:
      kubeadm_expression:
      - "kubeadm"
      - "join"
      - "--config=/tmp/kubeadm-join-config.yaml"
    include_role:
      name: helpers/kubeadm-command

  - name: Remove kubeadm-join-config.yaml
    file:
      path: /tmp/kubeadm-join-config.yaml
      state: absent

  # Workaround because it is currently not possible
  # to pass a kubelet config file for kubeadm join
  # https://stackoverflow.com/questions/60378117/limit-the-number-of-pods-per-node
  - name: Configure kubelet
    include_role:
      name: kubelet-configuration

  - name: Set static fact that kubernetes is initialized
    vars:
      content:
        k8s_install_status: "initialized"
    copy:
      dest: /etc/ansible/facts.d/kubernetes-initialized.fact
      owner: root
      group: root
      mode: 0644
      content: "{{ content | to_json }}"

# See docs ref:cluster.node-labeling
- name: "Ensure managed K8s node labels"
  delegate_to: "{{ groups['orchestrator'] | first }}"
  vars:
    # Dict of configured + gpu related + managed node labels to apply after join
    # managed labels take precedence
    node_labels: >
      {{
        (
          dict(
              k8s_node_labels[inventory_hostname] | default([])
              | map('split', '=', 1)
          )
          | combine(
            (k8s_is_gpu_cluster and not k8s_virtualize_gpu and ansible_local['gpu-node']['node_has_gpu'] | bool)
            | ternary({"k8s.yaook.cloud/gpu-node": "true"}, {})
          )
          | combine(_managed_node_labels['workers'])
        )
      }}
  when: node_labels | length > 0
  kubernetes.core.k8s:
    state: patched
    api_version: v1
    kind: Node
    name: "{{ inventory_hostname }}"
    definition:
      metadata:
        labels: "{{ node_labels }}"

- name: "Ensure K8s node taints"
  delegate_to: "{{ groups['orchestrator'] | first }}"
  vars:
    # List of configured + gpu related node taints (as dicts) to apply after join
    # (taint strings parsed to dict,
    #  empty values are omitted, effect defaults to NoExecute)
    node_taints: >
      {{
        (
          k8s_node_taints[inventory_hostname] | default([])
          | map('regex_replace', '^([^:=]+)([=]([^:]+))?([:](.+))?', '{"key": "\1", "value": "\3", "effect": "\5"}')
          | map('regex_replace', ', "value": ""', '')
          | map('regex_replace', '"effect": ""', '"effect": "NoExecute"')
          | map('from_json')
        )
        +
          (
            (k8s_is_gpu_cluster and not k8s_virtualize_gpu and ansible_local['gpu-node']['node_has_gpu'] | bool)
            | ternary([{"key": "k8s.yaook.cloud/gpu-node", "value": "true", "effect": "NoSchedule"}], [])
          )
      }}
  when:
  - node_taints | length > 0
  kubernetes.core.k8s_taint:
    state: present
    name: "{{ inventory_hostname }}"
    taints: "{{ node_taints }}"
...
