---
- name: Read S3 secrets from Vault
  environment:
    ANSIBLE_HASHI_VAULT_URL: "{{ lookup('env', 'VAULT_ADDR') }}"
    ANSIBLE_HASHI_VAULT_CA_CERT: "{{ lookup('env', 'VAULT_CACERT') }}"
  vars:
    vault_auth_mount_point: "{{ lookup('env', 'VAULT_AUTH_PATH') }}"
    vault_auth_method: "{{ lookup('env', 'VAULT_AUTH_METHOD') or (lookup('env', 'VAULT_TOKEN') | ternary('token', 'approle')) }}"
    vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"
    vault_role_id: "{{ lookup('env', 'VAULT_ROLE_ID') }}"
    vault_secret_id: "{{ lookup('env', 'VAULT_SECRET_ID') }}"
  set_fact:
    etcd_backup_config: "{{ lookup('community.hashi_vault.vault_kv2_get', etcd_backup_vault_path, engine_mount_point=etcd_backup_vault_mount_point, mount_point=vault_auth_mount_point, auth_method=vault_auth_method, token=vault_token, role_id=vault_role_id, secret_id=vault_secret_id).data.data }}"

- name: Create a Secret to save s3 credentials
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ etcd_backup_helm_values.targets.s3.credentialRef.name }}"
        namespace: "{{ etcd_backup_helm_release_namespace }}"
      data:
        access: "{{ etcd_backup_config.access_key | b64encode }}"
        secret: "{{ etcd_backup_config.secret_key | b64encode }}"
    validate:
      fail_on_error: true
  # Retry this task on failures
  register: k8s_apply
  until: k8s_apply is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"

- name: Deploy yaook operator etcd backup chart
  kubernetes.core.helm:
    chart_repo_url: "{{ etcd_backup_helm_chart_repo_url }}"
    chart_ref: "{{ etcd_backup_helm_chart_ref }}"
    chart_version: "{{ etcd_backup_helm_chart_version }}"
    release_namespace: "{{ etcd_backup_helm_release_namespace }}"
    release_name: "{{ etcd_backup_helm_release_name }}"
    release_state: present
    values: |
      {{ etcd_backup_helm_values | ansible.builtin.combine(
        {
          'targets': {'s3': {'endpoint': etcd_backup_config.endpoint_url}},
          'certRef': etcd_backup_config.certRef
        }, recursive=true
      ) }}
...
