---
- name: Populate service facts
  service_facts:

- name: Disable strongswan
  become: true
  systemd:
    name: "{{ strongswan_service }}"
    state: stopped
    enabled: false
  when: ansible_facts.services['strongswan-swanctl.service'] is defined

- name: Purge the IPsec setup
  become: true
  apt:
    name: "charon-systemd"
    state: absent
    purge: true
    autoremove: true
  register: task_result
  until: task_result is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"

- name: Remove charon-systemd.conf
  become: true
  file:
    path: /etc/strongswan.d/charon-systemd.conf
    state: absent

- name: Remove swanctl.conf
  become: true
  file:
    path: /etc/swanctl/swanctl.conf
    state: absent

- name: Remove BIRD configuration
  become: true
  file:
    state: absent
    path: /etc/bird.d/10-ipsec-vpn.conf
  notify: restart bird

- name: Remove nftables configuration
  become: true
  file:
    state: absent
    path: /etc/nft.d/10-ipsec-vpn.conf
  notify: reload nftables

- name: Remove keepalived configuration
  become: true
  file:
    state: absent
    path: /etc/keepalived/scripts/10-swanctl-notify.sh
  notify: restart keepalived

- name: Delete IPSec EAP PSK from vault
  delegate_to: "{{ groups['orchestrator'] | first }}"
  environment:
    ANSIBLE_HASHI_VAULT_URL: "{{ lookup('env', 'VAULT_ADDR') }}"
    ANSIBLE_HASHI_VAULT_CA_CERT: "{{ lookup('env', 'VAULT_CACERT') }}"
  block:
  - name: "Check availability of IPSec EAP PSK in Vault: Fetch key"
    no_log: true  # prevent private key from being exposed
    community.hashi_vault.vault_kv2_get:
      path: ipsec-eap-psk
      engine_mount_point: "{{ vault_path_prefix }}/{{ vault_cluster_name }}/kv"
      mount_point: "{{ vault_nodes_approle }}"
      auth_method: approle
      role_id: "{{ vault_node_role_id }}"
      secret_id: "{{ vault_node_secret_id }}"
      token_validate: false
    register: get_ipsec_eap_psk
    ignore_errors: true

  - set_fact:
      ipsec_eap_psk_avail_in_vault: >
        {{ (get_ipsec_eap_psk is success)
           and ((get_ipsec_eap_psk.data.data.ipsec_eap_psk | default("")) != "") }}

  - name: "Print availability of CA key in Vault"
    debug:
      msg: >
        IPSec EAP PSK is
        {{ ipsec_eap_psk_avail_in_vault | ternary(
          'still available in Vault and should be deleted',
          'already deleted in Vault'
        ) }}.

  # NOTE: We don't require explicit consent here as the deletion is not
  #       actually destructive. Users are able to undelete.
  - name: Ensure IPSec EAP PSK is removed from Vault
    no_log: true  # prevent private key from being exposed
    # NOTE: We only attempt to delete when there is actually something to delete
    #       so that a Vault root token only needs to be present in this case.
    when: ipsec_eap_psk_avail_in_vault
    community.hashi_vault.vault_kv2_delete:
      path: ipsec-eap-psk
      engine_mount_point: "{{ vault_path_prefix }}/{{ vault_cluster_name }}/kv"
      # NOTE: Because the Vault role 'k8s-control-plane' is not allowed to
      #       delete the IPSec EAP PSK in Vault, we need to use the priviledges of
      #       the caller. Currently it must insert a Vault root token here.
      auth_method: "{{ vault_caller_auth_method }}"
      mount_point: "{{ vault_caller_auth_mount_point }}"
      token: "{{ vault_caller_token }}"
      role_id: "{{ vault_caller_role_id }}"
      secret_id: "{{ vault_caller_secret_id }}"
      token_validate: false

  rescue:
  - name: "Ensure IPSec EAP PSK is removed from Vault: Hint failure reason"
    fail:
      msg: |
        Vault root token required!
        Disabling IPSec entails the removal of the EAP PSK from Vault's key-value store.
        This is done by the orchestrator and requires a Vault root token.

        Before restarting the run, either
        a) export a Vault root token (not recommended)
        or b) manually remove the secret from Vault:

        $ VAULT_TOKEN=$vault_root_token vault kv delete {{ vault_path_prefix }}/{{ vault_cluster_name }}/kv/ipsec-eap-psk

- name: Remove ipsec subdirectory in the inventory
  become: false
  delegate_to: "{{ groups['orchestrator'] | first }}"
  run_once: true
  file:
    path: "{{ etc_dir }}/ipsec/"
    state: absent
...
