---
- name: Load the unseal keys
  block:
    - name: Load the unseal keys (may fail gracefully)
      no_log: true  # prevent unseal key from being exposed
      set_fact:
        openbao_on_k8s_unseal_keys: "{{ lookup('file', etc_dir + '/openbao/unseal.key') | from_json }}"
      ignore_errors: true
      register: load_keys
    - name: Ensure the unseal key variable is defined
      when: load_keys.failed
      set_fact:
        openbao_on_k8s_unseal_keys: []

- name: Load the token
  block:
    - name: Load the root token (may fail gracefully)
      no_log: true  # prevent root token from being exposed
      set_fact:
        openbao_on_k8s_root_token: "{{ lookup('file', etc_dir + '/openbao/root.token') }}"
      ignore_errors: true
      register: load_token
...
