---
- name: Set openbao server DNS names
  set_fact:
    openbao_on_k8s_dnsnames_complete: |
      [
        {% for name in openbao_on_k8s_dnsnames %} {{ name | to_json }}, {% endfor %}
      ]

- name: Create Openbao Certificate (external)
  kubernetes.core.k8s:
    apply: true
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        namespace: "{{ openbao_on_k8s_namespace }}"
        name: openbao-cert-external
      spec:
        issuerRef:
          name: "{{ openbao_on_k8s_external_ingress_issuer_name }}"
          kind: "{{ openbao_on_k8s_external_ingress_issuer_kind }}"
        secretName: openbao-cert-external
        dnsNames: "{{ openbao_on_k8s_dnsnames_complete }}"
    validate:
      fail_on_error: true
      strict: true
  # Retry this task on failures
  register: k8s_apply
  until: k8s_apply is not failed
  retries: 20
  delay: 15

- name: Create another API endpoint
  # Retry this task on failures
  register: k8s_apply
  until: k8s_apply is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"
  kubernetes.core.k8s:
    apply: true
    validate:
      fail_on_error: true
      strict: true
    definition: "{{ lookup('template', 'api-service.yaml.j2') }}"

- name: Create Openbao Ingress (external)
  kubernetes.core.k8s:
    apply: true
    definition: "{{ lookup('template', 'external_ingress.yaml.j2') }}"
    validate:
      fail_on_error: true
      strict: true
  # Retry this task on failures
  register: k8s_apply
  until: k8s_apply is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"
...
