---
- name: Create Openbao CA selfsigned issuer (internal)
  # Retry this task on failures
  register: k8s_apply
  until: k8s_apply is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"
  kubernetes.core.k8s:
    apply: true
    definition:
      apiVersion: cert-manager.io/v1
      kind: "{{ openbao_on_k8s_ca_issuer_kind }}"
      metadata:
        name: "{{ openbao_on_k8s_ca_issuer }}"
        namespace: "{{ openbao_on_k8s_namespace }}"
      spec:
        selfSigned: {}
    validate:
      fail_on_error: true
      strict: true

- name: Create Openbao CA (internal)
  # Retry this task on failures
  register: k8s_apply
  until: k8s_apply is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"
  kubernetes.core.k8s:
    apply: true
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        namespace: "{{ openbao_on_k8s_namespace }}"
        name: openbao-ca-internal
      spec:
        issuerRef:
          kind: "{{ openbao_on_k8s_ca_issuer_kind }}"
          name: "{{ openbao_on_k8s_ca_issuer }}"
        secretName: openbao-ca-internal
        commonName: openbao-ca-internal
        isCA: true
    validate:
      fail_on_error: true
      strict: true

- name: Create Openbao Issuer (internal)
  # Retry this task on failures
  register: k8s_apply
  until: k8s_apply is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"
  kubernetes.core.k8s:
    apply: true
    definition:
      apiVersion: cert-manager.io/v1
      kind: Issuer
      metadata:
        namespace: "{{ openbao_on_k8s_namespace }}"
        name: openbao-internal
      spec:
        ca:
          secretName: openbao-ca-internal
    validate:
      fail_on_error: true
      strict: true

- name: Enumerate workers
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
  register: nodes
  # Retry this task on failures
  until: nodes is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"

- name: Collect worker IPs
  set_fact:
    openbao_on_k8s_worker_ips: "{{ (nodes.resources | map(attribute='status') | map(attribute='addresses') | flatten(levels=1) | selectattr('type', 'eq', 'InternalIP') | map(attribute='address')) }}"

- name: Set openbao server DNS names
  set_fact:
    openbao_on_k8s_dnsnames_complete: |
      [
        {{ "openbao.%s.svc.cluster.local" | format(openbao_on_k8s_namespace) | to_json }},
        {{ "openbao-active.%s.svc.cluster.local" | format(openbao_on_k8s_namespace) | to_json }},
      ]

- name: Create Openbao Certificate (internal)
  # Retry this task on failures
  register: k8s_apply
  until: k8s_apply is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"
  # This needs to be valid for:
  # - the cluster service name
  # - all worker IP addresses (if management cluster integration)
  # - possibly a fun public DNS name
  kubernetes.core.k8s:
    apply: true
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        namespace: "{{ openbao_on_k8s_namespace }}"
        name: openbao-cert-internal
      spec:
        issuerRef:
          name: openbao-internal
        secretName: openbao-cert-internal
        duration: 72h
        renewBefore: 24h
        ipAddresses: "{{ (openbao_on_k8s_service_type in ['NodePort', 'LoadBalancer']) | ternary(openbao_on_k8s_worker_ips, []) + ['127.0.0.1', '::1'] }}"
        dnsNames: "{{ openbao_on_k8s_dnsnames_complete }}"
    validate:
      fail_on_error: true
      strict: true
...
