---
- name: Fetch the status of {{ pod.metadata.name }}
  kubernetes.core.k8s_exec:
    namespace: "{{ openbao_on_k8s_namespace }}"
    pod: "{{ pod.metadata.name }}"
    container: openbao
    command: bao status -format=json
  register: bao_status
  failed_when: bao_status.rc not in [0, 2]

- name: Abort if openbao is sealed and we don't have any keys ({{ pod.metadata.name }})
  when: (bao_status.stdout | from_json).sealed and not openbao_on_k8s_unseal_keys
  fail:
    msg: Dear user, the LCM would like to speak with our Openbao. Unfortuntely it's locked and you didn't hand us the key(s). Mind helping us out by unsealing the Openbao manually? Thanks!

# We don't care that the unseal keys are exposed because they are supposed to be rotated anyway after the initial setup.
- name: Unseal {{ pod.metadata.name }}
  when: (bao_status.stdout | from_json).sealed
  kubernetes.core.k8s_exec:
    namespace: "{{ openbao_on_k8s_namespace }}"
    pod: "{{ pod.metadata.name }}"
    container: openbao
    command: "bao operator unseal {{ item | quote }}"
  register: bao_unseal
  until: bao_unseal.rc == 0
  timeout: 120
  retries: "{{ error_retries }}"
  loop: "{{ openbao_on_k8s_unseal_keys[:openbao_on_k8s_init_key_threshold] }}"
  loop_control:
    label: Redacted
...
