---
collections:
  - name: devsec.hardening
    version: 10.6.0
  - name: kubernetes.core
    version: 6.4.0
  - name: community.general
    version: 13.1.0
  - name: ansible.posix
    version: 2.2.1
...
