---
- name: Prepare kubeadm-patches
  become: true
  block:
    - name: Create kubeadm-patches folder
      file:
        path: "{{ k8s_kubeadm_patches_remote_dir }}"
        state: directory
        owner: root
        group: root
        mode: '750'

    - name: Synchronize kubeadm patch files
      ansible.posix.synchronize:
        src: "{{ k8s_kubeadm_patches_dir }}/"
        dest: "{{ k8s_kubeadm_patches_remote_dir }}"
        owner: false
        copy_links: true
        perms: false
        delete: true
        rsync_opts:
          - "--chown=root:root"
          - "--chmod=F440"
          - "--ignore-times"  # important as the file stamps in the Nix store are all the same
...
