---
- name: Prepare kubeadm-patches
  become: true
  block:
    - name: Upload audit log policy file
      copy:
        src: "{{ k8s_apiserver_audit_logs_policy_file }}"
        dest: /etc/kubernetes/audit-policy.yaml
        owner: root
        group: root
        mode: '0640'
      when: k8s_apiserver_audit_logs_enabled

    - name: Remove audit log policy file
      file:
        state: absent
        path: "/etc/kubernetes/audit-policy.yaml"
      when: not k8s_apiserver_audit_logs_enabled

    - name: Create kubeadm-patches folder
      file:
        path: /etc/kubernetes/kubeadm-patches
        state: directory
        owner: root
        group: root
        mode: '750'

    - name: Upload kube-apiserver patches
      template:
        src: templates/kubeadm-patches/kube-apiserver0+json.json.j2
        dest: /etc/kubernetes/kubeadm-patches/kube-apiserver0+json.json
        owner: root
        group: root
        mode: '440'
...
