---
- name: "Create cert-manager resources for OpenBao's PKI"
  delegate_to: "{{ groups['orchestrator'] | first }}"
  kubernetes.core.k8s:
    src: "{{ openbao_on_k8s.pki.cert-manager.manifest_file_path }}"
    state: present
    apply: true
    append_hash: false
    validate:
      fail_on_error: true
      strict: true
  register: _k8s_create_pki_cert-manager
  until: _k8s_create_pki_cert-manager is not failed
  retries: "{{ error_retries }}"
  delay: "{{ error_delay }}"
...
