---
# This role triggers all "verify-*.sh" action scripts
- name: Find all "verify-*.sh" scripts
  delegate_to: "{{ groups['orchestrator'] | first }}"
  run_once: true
  find:
    paths: "{{ playbook_dir }}/../../actions"
    patterns: "verify-*.sh"
  register: script_list

- name: Trigger all "verify-*.sh" scripts  # noqa no-changed-when
  delegate_to: "{{ groups['orchestrator'] | first }}"
  command: "{{ item.path }}"
  run_once: true
  args:
    chdir: "{{ playbook_dir }}/../../../"
  environment:
    ANSIBLE_PYTHON_INTERPRETER: "{{ ansible_playbook_python }}"
  loop: "{{ script_list.files | sort(attribute='path') }}"
  loop_control:
    label: "{{ item.path }}"
...
